- name: create downloads dir
  file: name={{ admuser_downloads_dir }}/spark state=directory

- name: download spark
  get_url:
    url: http://d3kbcqa49mib13.cloudfront.net/spark-2.0.2-bin-hadoop2.7.tgz
    dest: "{{ admuser_downloads_dir }}/spark"

